[package]
name = "mmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy =  "0.11.2"
crossbeam-channel = "0.5.8"
mouse_position = "0.1.3"
multiinput = "0.1.0"
winapi = "0.3.9"

